import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { NextUiProvider } from "@/components/providers/nextui-provider";
import { Toaster } from "react-hot-toast";
import Sidebar from "./(main)/_components/sidebar";
import MobileSidebar from "./(main)/_components/mobile-sidebar";
import Navigation from "@/components/ui/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat with images",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MobileSidebar />
      {/* <Navigation /> */}
      <div className="flex overflow-y-hidden  bg-gray-100 max-h-screen gap-0 sm:gap-3 ">
        <div className=" lg:block hidden w-72 border bg-white ">
          <Sidebar />
        </div>
        {children}
      </div>
    </>
  );
}
