import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { NextUiProvider } from "@/components/providers/nextui-provider";
import { Toaster } from "react-hot-toast";
import Navigation from "@/components/ui/navigation";
import PreviewResumeResult from "@/components/pages/resume/preview-resume-result";
import TextArea from "@/components/pages/resume/text-area";
import DrapAndDrop from "@/components/pages/resume/drag-and-drop";
import ResumeList from "@/components/pages/resume/resume-list";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat with pdf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
     <div>{children}</div>
    </>
  );
}
